//不存在该该声明时默认为proto2

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: user.proto

//

package service

import (
	context "context"
	"github.com/jenson/county/core/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserRpc_Login_FullMethodName             = "/userService.userRpc/Login"
	UserRpc_SayHello_FullMethodName          = "/userService.userRpc/SayHello"
	UserRpc_GetUserDetailByID_FullMethodName = "/userService.userRpc/GetUserDetailByID"
)

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcClient interface {
	Login(ctx context.Context, in *models.LoginReq, opts ...grpc.CallOption) (*models.LoginResp, error)
	SayHello(ctx context.Context, in *models.GreetReq, opts ...grpc.CallOption) (*models.GreetResp, error)
	GetUserDetailByID(ctx context.Context, in *models.QueryUserDetailReq, opts ...grpc.CallOption) (*models.QueryUserDetailResp, error)
}

type userRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcClient(cc grpc.ClientConnInterface) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) Login(ctx context.Context, in *models.LoginReq, opts ...grpc.CallOption) (*models.LoginResp, error) {
	out := new(models.LoginResp)
	err := c.cc.Invoke(ctx, UserRpc_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) SayHello(ctx context.Context, in *models.GreetReq, opts ...grpc.CallOption) (*models.GreetResp, error) {
	out := new(models.GreetResp)
	err := c.cc.Invoke(ctx, UserRpc_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetUserDetailByID(ctx context.Context, in *models.QueryUserDetailReq, opts ...grpc.CallOption) (*models.QueryUserDetailResp, error) {
	out := new(models.QueryUserDetailResp)
	err := c.cc.Invoke(ctx, UserRpc_GetUserDetailByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
// All implementations must embed UnimplementedUserRpcServer
// for forward compatibility
type UserRpcServer interface {
	Login(context.Context, *models.LoginReq) (*models.LoginResp, error)
	SayHello(context.Context, *models.GreetReq) (*models.GreetResp, error)
	GetUserDetailByID(context.Context, *models.QueryUserDetailReq) (*models.QueryUserDetailResp, error)
	mustEmbedUnimplementedUserRpcServer()
}

// UnimplementedUserRpcServer must be embedded to have forward compatible implementations.
type UnimplementedUserRpcServer struct {
}

func (UnimplementedUserRpcServer) Login(context.Context, *models.LoginReq) (*models.LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserRpcServer) SayHello(context.Context, *models.GreetReq) (*models.GreetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedUserRpcServer) GetUserDetailByID(context.Context, *models.QueryUserDetailReq) (*models.QueryUserDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetailByID not implemented")
}
func (UnimplementedUserRpcServer) mustEmbedUnimplementedUserRpcServer() {}

// UnsafeUserRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServer will
// result in compilation errors.
type UnsafeUserRpcServer interface {
	mustEmbedUnimplementedUserRpcServer()
}

func RegisterUserRpcServer(s grpc.ServiceRegistrar, srv UserRpcServer) {
	s.RegisterService(&UserRpc_ServiceDesc, srv)
}

func _UserRpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).Login(ctx, req.(*models.LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).SayHello(ctx, req.(*models.GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetUserDetailByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.QueryUserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUserDetailByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUserDetailByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUserDetailByID(ctx, req.(*models.QueryUserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpc_ServiceDesc is the grpc.ServiceDesc for UserRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userService.userRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserRpc_Login_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _UserRpc_SayHello_Handler,
		},
		{
			MethodName: "GetUserDetailByID",
			Handler:    _UserRpc_GetUserDetailByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
